---
- name: Run TDX guest image
  hosts: host
  become: true
  tags:
    - run-vm
    - always
  handlers:
    - name: Global handlers
      ansible.builtin.import_tasks: "{{ playbook_dir }}/../handlers/main.yml"
  tasks:
    - name: Include run TDX vm role
      ansible.builtin.include_role:
        name: run-vm

- name: Common Setup
  hosts: vm
  become: true
  tags:
    - common
  handlers:
    - name: Global handlers
      ansible.builtin.import_tasks: "{{ playbook_dir }}/../handlers/main.yml"
  tasks:
    - name: Include common role
      ansible.builtin.include_role:
        name: common

- name: Setup K3S clusters
  hosts: vm
  become: true
  tags:
    - k3s
  handlers:
    - name: Global handlers
      ansible.builtin.import_tasks: "{{ playbook_dir }}/../handlers/main.yml"
  tasks:
    - name: Include k3s role
      ansible.builtin.include_role:
        name: k3s

- name: GPU Setup
  hosts: vm
  become: true
  tags:
    - gpu
  handlers:
    - name: Global handlers
      ansible.builtin.import_tasks: "{{ playbook_dir }}/../handlers/main.yml"
  tasks:
    - name: Include gpu role
      ansible.builtin.include_role:
        name: gpu

- name: GPU verification service
  hosts: vm
  become: true
  tags:
    - gpu-verify
  handlers:
    - name: Global handlers
      ansible.builtin.import_tasks: "{{ playbook_dir }}/../handlers/main.yml"
  tasks:
    - name: GPU verification service
      ansible.builtin.include_role:
        name: gpu-verify

- name: Setup Chutes GPU Clusters
  hosts: vm
  become: true
  tags:
    - chutes-gpu
  handlers:
    - name: Global handlers
      ansible.builtin.import_tasks: "{{ playbook_dir }}/../handlers/main.yml"
  tasks:
    - name: Setup GPU Node
      ansible.builtin.include_role:
        name: chutes-gpu
        apply:
          tags: chutes-gpu

- name: Install sek8s
  hosts: vm
  become: true
  tags:
    - sek8s
  handlers:
    - name: Global handlers
      ansible.builtin.import_tasks: "{{ playbook_dir }}/../handlers/main.yml"
  tasks:
    - name: sek8s
      ansible.builtin.include_role:
        name: sek8s
        apply:
          tags: sek8s

- name: Setup attestation-service
  hosts: vm
  become: true
  tags:
    - attestation-service
  handlers:
    - name: Global handlers
      ansible.builtin.import_tasks: "{{ playbook_dir }}/../handlers/main.yml"
  tasks:
    - name: Attestation service
      ansible.builtin.include_role:
        name: attestation-service
        apply:
          tags: attestation-service

- name: Setup admission controller
  hosts: vm
  become: true
  tags:
    - admission-controller
  handlers:
    - name: Global handlers
      ansible.builtin.import_tasks: "{{ playbook_dir }}/../handlers/main.yml"
  tasks:
    - name: Admission controller
      ansible.builtin.include_role:
        name: admission-controller
        apply:
          tags: admission-controller

- name: Setup system manager service (status + cache)
  hosts: vm
  become: true
  tags:
    - system-manager
  handlers:
    - name: Global handlers
      ansible.builtin.import_tasks: "{{ playbook_dir }}/../handlers/main.yml"
  tasks:
    - name: System manager
      ansible.builtin.include_role:
        name: system-manager
        apply:
          tags: system-manager

- name: Setup cache volume service
  hosts: vm
  become: true
  tags:
    - cache-volume
  handlers:
    - name: Global handlers
      ansible.builtin.import_tasks: "{{ playbook_dir }}/../handlers/main.yml"
  tasks:
    - name: Cache volume setup
      ansible.builtin.include_role:
        name: cache-volume
        apply:
          tags: cache-volume

- name: Add dyanmic config services
  hosts: vm
  become: true
  any_errors_fatal: false
  tags:
    - config
  handlers:
    - name: Global handlers
      ansible.builtin.import_tasks: "{{ playbook_dir }}/../handlers/main.yml"
  tasks:
    - name: Config
      ansible.builtin.include_role:
        name: config
        apply:
          tags: config

- name: Remove remote access
  hosts: vm
  become: true
  tags:
    - harden-access
  handlers:
    - name: Global handlers
      ansible.builtin.import_tasks: "{{ playbook_dir }}/../handlers/main.yml"
  tasks:
    - name: Remove remote access
      ansible.builtin.include_role:
        name: harden-access
        apply:
          tags: harden-access
      when: not debug_build | default(false)

- name: Security Hardening
  hosts: vm
  become: true
  tags:
    - security
  handlers:
    - name: Global handlers
      ansible.builtin.import_tasks: "{{ playbook_dir }}/../handlers/main.yml"
  tasks:
    - name: Include security role
      ansible.builtin.include_role:
        name: security

- name: Cleanup to ensure fresh state for cloud init and k3s
  hosts: all
  become: true
  any_errors_fatal: false
  tags:
    - cleanup
  handlers:
    - name: Global handlers
      ansible.builtin.import_tasks: "{{ playbook_dir }}/../handlers/main.yml"
  tasks:
    - name: Cleanup
      ansible.builtin.include_role:
        name: cleanup
        apply:
          tags: cleanup

- name: Encrypt disk
  hosts: host
  become: true
  tags:
    - luks
  handlers:
    - name: Global handlers
      ansible.builtin.import_tasks: "{{ playbook_dir }}/../handlers/main.yml"
  tasks:
    - name: Encrypt disk
      ansible.builtin.include_role:
        name: luks
        apply:
          tags: luks
      when: not debug_build | default(false)

- name: Prime VM for stable TDX measurements
  hosts: host
  become: true
  tags:
    - prime-vm
  handlers:
    - name: Global handlers
      ansible.builtin.import_tasks: "{{ playbook_dir }}/../handlers/main.yml"
  tasks:
    - name: Include prime VM role
      ansible.builtin.include_role:
        name: prime-vm
        apply:
          tags: prime-vm
      when: prime_vm_after_build | default(true)
